api/urls.py
from django.urls import path
from api.views import MyObtainTokenPairView, RegisterView
from rest_framework_simplejwt.views import TokenRefreshView


urlpatterns = [
    path('login/', MyObtainTokenPairView.as_view(), name='token_obtain_pair'),
    path('login/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('register/', RegisterView.as_view(), name='auth_register'),
]

dvor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('frontend.urls')),
    path('api/', include('api.urls'))
]

frontend/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.urls import path
from . import views

app_name = 'frontend'

urlpatterns = [
	path('all/', views.all_users, name = 'all_users'),
	path('r/', views.registration, name = 'registration'),
	path('r/comp/', views.complete_registration, name = 'complete'),
	path('l/', views.login_page, name = "login_page"),
	path('logout/', views.logout_page, name='logout_page'),
	path('<str:username>', views.user, name='user'),
]

api/models.py
from django.db import models

# Create your models here.

core/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.db.models.signals import post_save

from django.dispatch import receiver

# Create your models here. Okay.

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
	sex = models.BooleanField('Пол человека', default=False) #False - Девушка. True - Парень
	address = models.CharField('Адрес', max_length = 100, blank=True, null=True)
	bthd = models.DateField('Дата рождения', null=True, blank=True)

	def __str__(self):
		return str(self.user.username)
	
	def age(self):
		date = self.bthd
		return datetime.date.today().year - date.year - ((datetime.date.today().month, datetime.date.today().day) < (date.month, date.day))

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
	instance.profile.save()

core/forms.py
from django.contrib.auth.models import User
from .models import Profile
from django import forms
import datetime

class RegistrationForm(forms.Form):

	username =  forms.CharField(widget=forms.TextInput(), required=True)
	email = forms.EmailField(required=True)
	password = forms.CharField(widget=forms.PasswordInput())
	password2 = forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model = User
		fields = (
			'__all__'
		)

	def clean(self):
		
		username = self.cleaned_data["username"]
		email = self.cleaned_data["email"]
		password = self.cleaned_data["password"]
		password2 = self.cleaned_data["password2"]

		if password != password2:
			raise forms.ValidationError("Пароли не совпадают.")

		# Check user exist
		email_taken = User.objects.filter(email=email)

		if email_taken:
			raise forms.ValidationError({'email':["Такая почта уже существует."]})
		
		# Check username exist
		username_taken = User.objects.filter(username = username)
		if username_taken:
			raise forms.ValidationError({'username':["Такой ник уже существует."]})

		if password:
			if len(password) < 5:
				raise forms.ValidationError("Пароль слишком простой (не менее 5 символов).")

		return self.cleaned_data

class DateInput(forms.DateInput):
	input_type = 'date'

class CompleteRegistrationForm(forms.Form):
	#username = forms.CharField(label="Имя пользователя", max_length =100)
	address = forms.CharField(label="Адрес", max_length=100)
	bthd = forms.DateField(widget = DateInput)

	sex_choice = (
		(True, 'Мужчина'),
		(False,'Женщина')
	)

	sex = forms.ChoiceField(choices = sex_choice)

	class Meta:
		model = Profile
		widgets = {'bthd' : DateInput() }
		fields = (
			'__all__'
		)

	def clean(self):
		#username = self.cleaned_data['username']
		address = self.cleaned_data['address']
		bthd = self.cleaned_data['bthd']
		sex = self.cleaned_data['sex']

		if bthd > datetime.date.today():
			raise forms.ValidationError('Неправильная дата рождения')

		if datetime.date.today().year - bthd.year - ((datetime.date.today().month, datetime.date.today().day) < (bthd.month, bthd.day)) <=14:
			raise forms.ValidationError('Вход только с 15')

		return self.cleaned_data

class LoginForm(forms.Form):
	username = forms.CharField(label="Имя пользователя", max_length =100)
	password = forms.CharField(widget=forms.PasswordInput())
	class Meta:
		model = User
		fields = (
			'__all__'
		)
	
	def clean(self):
		username = self.cleaned_data['username']
		password = self.cleaned_data['password']

		# Check username exist
		username_taken = User.objects.filter(username = username)
		if not username_taken:
			raise forms.ValidationError({'username':["Такого ника нет."]})
		
		return self.cleaned_data

api/views.py
from .serializers import MyTokenObtainPairSerializer
from rest_framework.permissions import AllowAny
from rest_framework_simplejwt.views import TokenObtainPairView
from django.contrib.auth.models import User
from .serializers import RegisterSerializer
from rest_framework import generics

class MyObtainTokenPairView(TokenObtainPairView):
	permission_classes = (AllowAny,)
	serializer_class = MyTokenObtainPairSerializer

class RegisterView(generics.CreateAPIView):
    queryset = User.objects.all()
    permission_classes = (AllowAny,)
    serializer_class = RegisterSerializer

frontend/views.py
from urllib.parse import parse_qsl
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.urls import reverse


from core.models import Profile
from core.forms import RegistrationForm, CompleteRegistrationForm, LoginForm

# Create your views here. Okay.

def all_users(request):

	all = User.objects.all()
	return render(request, 'users/list.html', {'users': all})

def registration(request):

	form = RegistrationForm(request.POST or None)
	if request.POST and form.is_valid():
		username = form.cleaned_data['username']
		email = form.cleaned_data['email']
		password = form.cleaned_data['password']

		user = User.objects.create_user(username, email, password)
		login(request, user)

		prof = User.objects.get(username__exact = request.user)
		prof.save()

		return HttpResponseRedirect(reverse("frontend:complete"))
	return render(request,'users/register.html',{'form':form})

def complete_registration(request):

	form = CompleteRegistrationForm(request.POST or None)
	if request.POST and form.is_valid():
		prof = User.objects.get(username__exact = request.user)
		prof.profile.sex = form.cleaned_data['sex']
		prof.profile.address = form.cleaned_data['address']
		prof.profile.bthd = form.cleaned_data['bthd']
		prof.save()
		return HttpResponseRedirect(reverse("frontend:user", args = [prof.username]))
	return render(request,'users/r_complete.html',{'form':form})

def user(request, username):

	try:
		user = User.objects.get(username__exact = username)
	except:
		return HttpResponse('<h1>Такого пользователя не существует</h1>')

	contex = {'usr': user}
	return render(request,'users/page.html',contex)

def login_page(request):

	form = LoginForm(request.POST or None); err = False
	if request.POST and form.is_valid():
		username = form.cleaned_data['username']
		password = form.cleaned_data['password']

		user = authenticate(request=request, username = username, password = password)
		if user is not None:
			login(request, user)
			return HttpResponseRedirect(reverse("frontend:user", args = [user.username]))
		else:
			err = True
	return render(request,'users/login_page.html',{'form':form, 'err': err})

def logout_page(request):
	logout(request)
	return HttpResponseRedirect(reverse("frontend:all_users"))

frontend/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}Blank{% endblock %}</title>
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

frontend/templates/users/list.html
{% extends 'base.html' %}

{% block title%}
    Все пользователи
{% endblock %}

{% block content%}
    <h1>Зарегистрированны:</h1>
    {% if users %}
        {% for user2 in users %}
            {% if user.username == user2.username %}
                <h2 style="color: green">{{user2.username}}</h2>
            {% else %}
                <h2>{{user2.username}}</h2>
            {% endif %}
        {% endfor %}
    {% else %}
        <h2>Нет пользователей</h2>
    {% endif %}
{% endblock %}

frontend/templates/users/login_page.html
{% extends 'base.html' %}

{% block title%}
    Страница входа
{% endblock %}

{% block content%}
    <h1>Вход</h1>
    <form  method="POST">
        {% csrf_token %}

        {% if err %}
            <p>Неправильный логин или пароль</p>
        {% endif %}

        {{ form.as_p }}
        <button type="submit">Войти</button>
    </form>
{% endblock %}

frontend/templates/users/page.html
{% extends 'base.html' %}

{% block title%}
	{{ usr.username }}
{% endblock %}

{% block content%}

	{% if user.username == usr.username %}
		<h1>Это вы!</h1>
		<a href="{% url 'frontend:logout_page' %}">Выйти</a>
		<br>
	{% endif %}

	{% if usr.profile.online %}
		<h5>В сети</h5>
	{% else %}
		<b>Был в сети в </b> {{ usr.last_login }}
	{% endif %}
	<hr>

	<h1>Профиль</h1>
	<p> Адрес: {{usr.profile.address}} </p>
	<p> Почта: {{usr.email}} </p>
	<p> Пол: 
		{% if usr.profile.sex %}
			Мужской
		{% else %}
			Женский
		{% endif %}
	</p>
	<p> Дата рождения: {{ usr.profile.bthd }}</p>
	<b>Дата регистрации: </b> {{ usr.date_joined}}
{% endblock %}

frontend/templates/users/r_complete.html
{% extends 'base.html' %}

{% block title %}
    Завершите регистрацию
{% endblock %}

{% block content %}
    <h1>Завершите регистрацию</h1>
    <form  method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Подтвердить</button>
    </form>
{% endblock %}

frontend/templates/users/register.html
{% extends 'base.html' %}

{% block titile %}
    Регистрация
{% endblock %}

{% block content %}
    <h1>Регистрация</h1>
    <form  method="POST">
	    {% csrf_token %}
	    {{ form.as_p }}
	    <button type="submit">Зарегистрироваться</button>
    </form>
{% endblock %}